version: '3.8'

services:
  web: # service name 
    build:
      dockerfile: Dockerfile
      context: ./
    volumes: 
      - ./backend:/Sistema_de_Notificacao_de_Notas_de_Provas/Sistema_de_Notificacao_de_Notas_de_Provas
    env_file: 
      - ./.env # name of the env file
    image: backend_app
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=notificacoes
    ports:
      - 5433:5432

volumes:
  postgres_data: